cmake_minimum_required( VERSION 3.28 )
project( bugle-package-consumer LANGUAGES CXX )
find_package( bugle 1.2 REQUIRED )
add_executable( consumer main.cpp )
target_link_libraries( consumer PRIVATE bugle::core bugle::bugle )
foreach( module console json profiler sysinfo )
    if( TARGET bugle::${module} )
        target_link_libraries( consumer PRIVATE bugle::${module} )
        string( TOUPPER "${module}" module_upper )
        target_compile_definitions( consumer PRIVATE "HAVE_${module_upper}" )
    endif()
endforeach()
enable_testing()
add_test( NAME consumer COMMAND consumer )
